# Generated by Django 2.2.4 on 2019-09-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=6)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='recruit.Task')),
            ],
        ),
        migrations.CreateModel(
            name='PassedTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(to='recruit.Answer')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passedtests', to='recruit.Recruit')),
            ],
        ),
    ]
