# Generated by Django 2.2.4 on 2019-09-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_answer_passedtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.CharField(max_length=256),
        ),
    ]
