# Generated by Django 2.2.4 on 2019-09-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_auto_20190904_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='passedtest',
            name='shadowhand',
            field=models.ManyToManyField(to='recruit.Sith'),
        ),
    ]
