# Generated by Django 2.2.4 on 2019-09-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_passedtest_shadowhand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passedtest',
            name='shadowhand',
        ),
        migrations.AddField(
            model_name='sith',
            name='shadowhand',
            field=models.ManyToManyField(to='recruit.PassedTest'),
        ),
    ]
