# Generated by Django 2.2.4 on 2019-09-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_auto_20190905_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
