# Generated by Django 2.2.4 on 2019-09-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0009_auto_20190905_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], max_length=20),
        ),
    ]
