# Generated by Django 2.2.4 on 2019-09-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0010_auto_20190905_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=6),
        ),
    ]
